# SPDX-FileCopyrightText: 2025 The Calyx Institute
# SPDX-FileCopyrightText: 2026 Aurora Pure contributors
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = [
    "README.md",
    "BUILDING.md",
    "NOTICE.md",
    "PRIVACY.md",
    "RELEASE_NOTES.md",
    "docs/screenshots/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2021-2025 Aurora OSS",
    "2023-2025 The Calyx Institute",
    "2026 Aurora Pure contributors",
]
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2023 Gradle, Inc."
SPDX-License-Identifier = "Apache-2.0"
