# SPDX-FileCopyrightText: 2024-2025 The Calyx Institute
# SPDX-FileCopyrightText: 2024-2025 Aurora OSS
# SPDX-FileCopyrightText: 2026 Aurora Pure contributors
# SPDX-License-Identifier: GPL-3.0-or-later

[versions]
activity = "1.13.0"
androidGradlePlugin = "9.2.0"
coil = "3.4.0"
composeBom = "2026.04.01"
composeMaterial = "1.5.0-alpha18"
core = "1.18.0"
gplayapi = "3.5.9"
junit = "4.13.2"
kotlin = "2.3.21"
lifecycle = "2.10.0"
okhttp = "5.3.2"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
auroraoss-gplayapi = { module = "com.auroraoss:gplayapi", version.ref = "gplayapi" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
junit = { module = "junit:junit", version.ref = "junit" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
